name: Release

on:
  push:
    tags:
      - "v*" # Trigger on version tags like v1.0.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: |
          # Add uv to the PATH
          export PATH="$HOME/.cargo/bin:$PATH"
          uv pip sync requirements.txt requirements-dev.txt

      - name: Run comprehensive test suite
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          nox -s all


  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          body: |
            ## Concordia CLI ${{ github.ref_name }}

            🎉 **New release ready!** All tests passed and quality checks completed.

            ### Installation
            ```bash
            pip install -r requirements.txt -r requirements-dev.txt
            python main.py init
            python main.py looker generate
            ```
          draft: false
          prerelease: false
          generate_release_notes: true
